# Generated by Django 3.0.5 on 2021-03-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210311_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dietary_Restrictions',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('restriction', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Health_Options',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Saved_Recipes',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=250)),
                ('recipe_url', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
