# Generated by Django 3.0.5 on 2021-03-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210311_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Dietary_Restrictions',
        ),
        migrations.DeleteModel(
            name='Health_Options',
        ),
    ]
