# Generated by Django 3.0.5 on 2021-03-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210312_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preferences',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
