# Generated by Django 3.0.5 on 2021-03-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210312_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='dietary_restrictions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
