# Generated by Django 3.1.7 on 2021-03-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_info_dietary_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_recipes',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saved_recipes',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
